/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Corpus Status */
        get: operations["corpus_status_api_v1_corpus_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Collections */
        get: operations["list_collections_api_v1_collections_get"];
        put?: never;
        /** Create Collection */
        post: operations["create_collection_api_v1_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collection */
        get: operations["get_collection_api_v1_collections__collection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Collection */
        patch: operations["patch_collection_api_v1_collections__collection_id__patch"];
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_collections__collection_id__items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_collections__collection_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_v1_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item Image */
        get: operations["get_item_image_api_v1_items__item_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Traditions */
        get: operations["list_traditions_api_v1_traditions_get"];
        put?: never;
        /** Create Tradition */
        post: operations["create_tradition_api_v1_traditions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interpretations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interpretations */
        get: operations["list_interpretations_api_v1_interpretations_get"];
        put?: never;
        /** Create Interpretation */
        post: operations["create_interpretation_api_v1_interpretations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correspondences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Correspondences */
        get: operations["list_correspondences_api_v1_correspondences_get"];
        put?: never;
        /** Create Correspondence */
        post: operations["create_correspondence_api_v1_correspondences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spreads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Spreads */
        get: operations["list_spreads_api_v1_spreads_get"];
        put?: never;
        /** Create Spread */
        post: operations["create_spread_api_v1_spreads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spreads/{spread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spread */
        get: operations["get_spread_api_v1_spreads__spread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Spread */
        patch: operations["patch_spread_api_v1_spreads__spread_id__patch"];
        trace?: never;
    };
    "/api/v1/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Readings */
        get: operations["list_readings_api_v1_readings_get"];
        put?: never;
        /** Create Reading */
        post: operations["create_reading_api_v1_readings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/{reading_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reading */
        get: operations["get_reading_api_v1_readings__reading_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Reading */
        patch: operations["patch_reading_api_v1_readings__reading_id__patch"];
        trace?: never;
    };
    "/api/v1/readings/{reading_id}/casts/draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draw Cast */
        post: operations["draw_cast_api_v1_readings__reading_id__casts_draw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/{reading_id}/casts/iching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iching Cast */
        post: operations["iching_cast_api_v1_readings__reading_id__casts_iching_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/{reading_id}/casts/{cast_id}/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Placement */
        post: operations["create_placement_api_v1_readings__reading_id__casts__cast_id__placements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/{reading_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Note */
        post: operations["create_note_api_v1_readings__reading_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/{reading_id}/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Note */
        delete: operations["delete_note_api_v1_readings__reading_id__notes__note_id__delete"];
        options?: never;
        head?: never;
        /** Patch Note */
        patch: operations["patch_note_api_v1_readings__reading_id__notes__note_id__patch"];
        trace?: never;
    };
    "/api/v1/readings/{reading_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context */
        get: operations["get_context_api_v1_readings__reading_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CastOut */
        CastOut: {
            /** Id */
            id: string;
            /**
             * Cast Type
             * @enum {string}
             */
            cast_type: "collection" | "iching";
            /** Collection Id */
            collection_id: string | null;
            /** Deck Session Id */
            deck_session_id: string | null;
            /** Cast Order */
            cast_order: number;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Draw Results */
            draw_results: components["schemas"]["DrawResultOut"][];
            iching: components["schemas"]["IChingOut"] | null;
        };
        /** CollectionCreate */
        CollectionCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** System Type */
            system_type: string;
            /**
             * Supports Reversals
             * @default false
             */
            supports_reversals: boolean;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** CollectionOut */
        CollectionOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** System Type */
            system_type: string;
            /**
             * Supports Reversals
             * @default false
             */
            supports_reversals: boolean;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Item Count */
            item_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CollectionPatch */
        CollectionPatch: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Supports Reversals */
            supports_reversals?: boolean | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** ContextCast */
        ContextCast: {
            /** Id */
            id: string;
            /**
             * Cast Type
             * @enum {string}
             */
            cast_type: "collection" | "iching";
            /** Collection Id */
            collection_id: string | null;
            /** Deck Session Id */
            deck_session_id: string | null;
            /** Cast Order */
            cast_order: number;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Draw Results */
            draw_results: components["schemas"]["ContextDrawResult"][];
            iching: components["schemas"]["IChingOut"] | null;
        };
        /** ContextCorrespondence */
        ContextCorrespondence: {
            /** Id */
            id: string;
            /** Key */
            key: string | null;
            /** Item Id */
            item_id: string;
            /** Source Id */
            source_id: string;
            /** Tradition Id */
            tradition_id: string | null;
            /** Type */
            type: string;
            /** Value */
            value: string | null;
            /** Status */
            status: string;
            /** Locator */
            locator: string | null;
            /** Notes */
            notes: string | null;
        };
        /** ContextDrawResult */
        ContextDrawResult: {
            /** Id */
            id: string;
            /** Draw Order */
            draw_order: number;
            /**
             * Orientation
             * @enum {string}
             */
            orientation: "upright" | "reversed" | "none";
            item: components["schemas"]["DrawItemOut"];
            placement: components["schemas"]["PlacementOut"] | null;
            knowledge: components["schemas"]["ResultKnowledge"];
        };
        /** ContextInterpretation */
        ContextInterpretation: {
            /** Id */
            id: string;
            /** Key */
            key: string | null;
            /** Item Id */
            item_id: string;
            /** Source Id */
            source_id: string;
            /** Tradition Id */
            tradition_id: string | null;
            /** Interpretation Type */
            interpretation_type: string;
            /** Exact Text */
            exact_text: string;
            /** Locator */
            locator: string | null;
            /** Sequence */
            sequence: number | null;
            /** Notes */
            notes: string | null;
        };
        /** ContextSource */
        ContextSource: {
            /** Id */
            id: string;
            /** Key */
            key: string | null;
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /** Edition */
            edition: string | null;
            /** Publisher */
            publisher: string | null;
            /** Publication Year */
            publication_year: number | null;
            /** Language */
            language: string | null;
            /** Citation */
            citation: string | null;
            /** Source Url */
            source_url: string | null;
            /** Rights Status */
            rights_status: string | null;
            /** Notes */
            notes: string | null;
        };
        /** ContextTradition */
        ContextTradition: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /** CorpusStatus */
        CorpusStatus: {
            /** Rws Ready */
            rws_ready: boolean;
            /** Rws Item Count */
            rws_item_count: number;
            /** Iching Ready */
            iching_ready: boolean;
            /** Hexagram Count */
            hexagram_count: number;
            /** Iching Method Count */
            iching_method_count: number;
        };
        /** CorrespondenceCreate */
        CorrespondenceCreate: {
            /** Key */
            key: string;
            /** Item Id */
            item_id: string;
            /** Type */
            type: string;
            /** Value */
            value?: string | null;
            /** Tradition Id */
            tradition_id?: string | null;
            /** Source Id */
            source_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "attested" | "disputed" | "tradition_specific" | "not_applicable" | "not_attested" | "unknown";
            /** Locator */
            locator?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** CorrespondenceOut */
        CorrespondenceOut: {
            /** Key */
            key: string;
            /** Item Id */
            item_id: string;
            /** Type */
            type: string;
            /** Value */
            value?: string | null;
            /** Tradition Id */
            tradition_id?: string | null;
            /** Source Id */
            source_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "attested" | "disputed" | "tradition_specific" | "not_applicable" | "not_attested" | "unknown";
            /** Locator */
            locator?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DrawItemOut */
        DrawItemOut: {
            /** Id */
            id: string;
            /** Collection Id */
            collection_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Display Name */
            display_name: string | null;
            /** Sequence */
            sequence: number | null;
            /** Symbol */
            symbol: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** DrawRequest */
        DrawRequest: {
            /** Collection Id */
            collection_id: string;
            /** Count */
            count: number;
            /**
             * Reversals Enabled
             * @default false
             */
            reversals_enabled: boolean;
            /** Deck Session Id */
            deck_session_id?: string | null;
        };
        /** DrawResultOut */
        DrawResultOut: {
            /** Id */
            id: string;
            /** Draw Order */
            draw_order: number;
            /**
             * Orientation
             * @enum {string}
             */
            orientation: "upright" | "reversed" | "none";
            item: components["schemas"]["DrawItemOut"];
            placement: components["schemas"]["PlacementOut"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HexagramContext */
        HexagramContext: {
            /** Key */
            key: string | null;
            /** Canonical Number */
            canonical_number: number;
            /** Binary Pattern */
            binary_pattern: string;
            /** Chinese Name */
            chinese_name: string | null;
            /** Pinyin */
            pinyin: string | null;
            /** Legge Title */
            legge_title: string | null;
            /** Glyph */
            glyph: string | null;
            /** Texts */
            texts: components["schemas"]["IChingTextContext"][];
        };
        /** IChingCastRequest */
        IChingCastRequest: {
            /**
             * Method
             * @default three-coin
             * @enum {string}
             */
            method: "three-coin" | "yarrow-stalk" | "three_coin";
        };
        /** IChingKnowledge */
        IChingKnowledge: {
            primary: components["schemas"]["HexagramContext"] | null;
            relating: components["schemas"]["HexagramContext"] | null;
            /** Changing Lines */
            changing_lines: number[];
            /** Selection Notice */
            selection_notice: string;
        };
        /** IChingOut */
        IChingOut: {
            /**
             * Method
             * @enum {string}
             */
            method: "three-coin" | "yarrow-stalk";
            /**
             * Pattern Order
             * @constant
             */
            pattern_order: "bottom_to_top";
            /** Primary Pattern */
            primary_pattern: string;
            /** Changing Lines */
            changing_lines: number[];
            /** Relating Pattern */
            relating_pattern: string;
            /** Throws */
            throws: components["schemas"]["IChingThrowOut"][];
            knowledge?: components["schemas"]["IChingKnowledge"] | null;
        };
        /** IChingTextContext */
        IChingTextContext: {
            /** Key */
            key: string;
            /** Layer */
            layer: string;
            /** Unit Type */
            unit_type: string;
            /** Line Position */
            line_position: number | null;
            /** Section */
            section: string | null;
            /** Language */
            language: string;
            /** Source Id */
            source_id: string;
            /** Tradition Id */
            tradition_id: string | null;
            /** Exact Text */
            exact_text: string;
            /** Locator */
            locator: string;
            /** Sequence */
            sequence: number;
            /** Notes */
            notes: string | null;
        };
        /** IChingThrowOut */
        IChingThrowOut: {
            /** Line Number */
            line_number: number;
            /** Coins */
            coins: number[] | null;
            /** Line Value */
            line_value: number;
            /** Procedure */
            procedure?: {
                [key: string]: unknown;
            } | null;
        };
        /** InterpretationCreate */
        InterpretationCreate: {
            /** Key */
            key: string;
            /** Item Id */
            item_id: string;
            /** Source Id */
            source_id: string;
            /** Tradition Id */
            tradition_id?: string | null;
            /** Interpretation Type */
            interpretation_type: string;
            /** Exact Text */
            exact_text: string;
            /** Locator */
            locator?: string | null;
            /** Sequence */
            sequence?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** InterpretationOut */
        InterpretationOut: {
            /** Key */
            key: string;
            /** Item Id */
            item_id: string;
            /** Source Id */
            source_id: string;
            /** Tradition Id */
            tradition_id?: string | null;
            /** Interpretation Type */
            interpretation_type: string;
            /** Exact Text */
            exact_text: string;
            /** Locator */
            locator?: string | null;
            /** Sequence */
            sequence?: number | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ItemCreate */
        ItemCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Display Name */
            display_name?: string | null;
            /** Sequence */
            sequence?: number | null;
            /** Symbol */
            symbol?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** ItemOut */
        ItemOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Display Name */
            display_name?: string | null;
            /** Sequence */
            sequence?: number | null;
            /** Symbol */
            symbol?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Collection Id */
            collection_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** NoteCreate */
        NoteCreate: {
            /** Body */
            body: string;
        };
        /** NoteOut */
        NoteOut: {
            /** Body */
            body: string;
            /** Id */
            id: string;
            /** Reading Id */
            reading_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlacementCreate */
        PlacementCreate: {
            /** Draw Result Id */
            draw_result_id: string;
            /** Spread Id */
            spread_id?: string | null;
            /** Spread Position Id */
            spread_position_id?: string | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
            /** Rotation */
            rotation?: number | null;
        };
        /** PlacementOut */
        PlacementOut: {
            /** Id */
            id: string;
            /** Spread Id */
            spread_id: string | null;
            /** Spread Position Id */
            spread_position_id: string | null;
            /** X */
            x: number | null;
            /** Y */
            y: number | null;
            /** Rotation */
            rotation: number | null;
            /** Label */
            label: string | null;
        };
        /** PositionCreate */
        PositionCreate: {
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Rotation
             * @default 0
             */
            rotation: number;
            /** Order */
            order: number;
        };
        /** PositionOut */
        PositionOut: {
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Rotation
             * @default 0
             */
            rotation: number;
            /** Order */
            order: number;
            /** Id */
            id: string;
        };
        /** ReadingContext */
        ReadingContext: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Question */
            question: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Casts */
            casts: components["schemas"]["ContextCast"][];
            /** Notes */
            notes: components["schemas"]["NoteOut"][];
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["ContextSource"];
            };
            /** Traditions */
            traditions: {
                [key: string]: components["schemas"]["ContextTradition"];
            };
            /** Notice */
            notice: string;
        };
        /** ReadingCreate */
        ReadingCreate: {
            /** Title */
            title: string;
            /** Question */
            question?: string | null;
        };
        /** ReadingDetail */
        ReadingDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Question */
            question: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Casts */
            casts: components["schemas"]["CastOut"][];
            /** Notes */
            notes: components["schemas"]["NoteOut"][];
        };
        /** ReadingPatch */
        ReadingPatch: {
            /** Title */
            title?: string | null;
            /** Question */
            question?: string | null;
        };
        /** ReadingSummary */
        ReadingSummary: {
            /** Title */
            title: string;
            /** Question */
            question?: string | null;
            /** Id */
            id: string;
            /** Cast Count */
            cast_count: number;
            /** Cast Types */
            cast_types: ("collection" | "iching")[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ResultKnowledge */
        ResultKnowledge: {
            /** Applicable Interpretations */
            applicable_interpretations: components["schemas"]["ContextInterpretation"][];
            /** Other Interpretations */
            other_interpretations: components["schemas"]["ContextInterpretation"][];
            /** Correspondences */
            correspondences: components["schemas"]["ContextCorrespondence"][];
        };
        /** SourceCreate */
        SourceCreate: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Edition */
            edition?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Publication Year */
            publication_year?: number | null;
            /** Language */
            language?: string | null;
            /** Citation */
            citation?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Rights Status */
            rights_status?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Edition */
            edition?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Publication Year */
            publication_year?: number | null;
            /** Language */
            language?: string | null;
            /** Citation */
            citation?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Rights Status */
            rights_status?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SpreadCreate */
        SpreadCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Positions */
            positions: components["schemas"]["PositionCreate"][];
        };
        /** SpreadOut */
        SpreadOut: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SpreadPatch */
        SpreadPatch: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Positions */
            positions?: components["schemas"]["PositionCreate"][] | null;
        };
        /** TraditionCreate */
        TraditionCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** TraditionOut */
        TraditionOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    corpus_status_api_v1_corpus_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusStatus"];
                };
            };
        };
    };
    list_collections_api_v1_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"][];
                };
            };
        };
    };
    create_collection_api_v1_collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_api_v1_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_collection_api_v1_collections__collection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_collections__collection_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_collections__collection_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_image_api_v1_items__item_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/jpeg": unknown;
                };
            };
            /** @description Image not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traditions_api_v1_traditions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraditionOut"][];
                };
            };
        };
    };
    create_tradition_api_v1_traditions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TraditionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraditionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interpretations_api_v1_interpretations_get: {
        parameters: {
            query?: {
                item_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interpretation_api_v1_interpretations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterpretationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_correspondences_api_v1_correspondences_get: {
        parameters: {
            query?: {
                item_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrespondenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_correspondence_api_v1_correspondences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrespondenceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrespondenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_spreads_api_v1_spreads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpreadOut"][];
                };
            };
        };
    };
    create_spread_api_v1_spreads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpreadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spread_api_v1_spreads__spread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_spread_api_v1_spreads__spread_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpreadPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_readings_api_v1_readings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSummary"][];
                };
            };
        };
    };
    create_reading_api_v1_readings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reading_api_v1_readings__reading_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_reading_api_v1_readings__reading_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draw_cast_api_v1_readings__reading_id__casts_draw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrawRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CastOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iching_cast_api_v1_readings__reading_id__casts_iching_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IChingCastRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CastOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_placement_api_v1_readings__reading_id__casts__cast_id__placements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: string;
                cast_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_v1_readings__reading_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_v1_readings__reading_id__notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: string;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_note_api_v1_readings__reading_id__notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: string;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_context_api_v1_readings__reading_id__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
