"""integrate yijing corpus and yarrow casting

Revision ID: 4161cf9c9c18
Revises: 20f9193f9e81
Create Date: 2026-08-23 15:36:51.591758
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4161cf9c9c18"
down_revision: str | None = "20f9193f9e81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trigrams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("chinese_name", sa.String(length=20), nullable=False),
        sa.Column("pinyin", sa.String(length=40), nullable=False),
        sa.Column("glyph", sa.String(length=8), nullable=False),
        sa.Column("binary_pattern", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "replace(replace(binary_pattern, '0', ''), '1', '') = ''",
            name="ck_trigram_pattern_binary",
        ),
        sa.CheckConstraint("length(binary_pattern) = 3", name="ck_trigram_pattern_length"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("binary_pattern"),
        sa.UniqueConstraint("glyph"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "iching_methods",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("probabilities", sa.JSON(), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("locator", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "hexagram_lines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("hexagram_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("polarity", sa.String(length=8), nullable=False),
        sa.CheckConstraint("polarity IN ('yin','yang')", name="ck_hexagram_line_polarity"),
        sa.CheckConstraint("position BETWEEN 1 AND 6", name="ck_hexagram_line_position"),
        sa.ForeignKeyConstraint(["hexagram_id"], ["hexagrams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hexagram_id", "position", name="uq_hexagram_line_position"),
        sa.UniqueConstraint("key", name="uq_hexagram_line_key"),
    )
    op.create_table(
        "iching_relationships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("source_hexagram_id", sa.String(length=36), nullable=False),
        sa.Column("target_hexagram_id", sa.String(length=36), nullable=False),
        sa.Column("relationship_type", sa.String(length=40), nullable=False),
        sa.Column("line_position", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["source_hexagram_id"], ["hexagrams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_hexagram_id"], ["hexagrams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_iching_relationship_key"),
    )
    op.create_table(
        "iching_texts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=220), nullable=False),
        sa.Column("layer", sa.String(length=80), nullable=False),
        sa.Column("unit_type", sa.String(length=80), nullable=False),
        sa.Column("hexagram_id", sa.String(length=36), nullable=True),
        sa.Column("trigram_id", sa.String(length=36), nullable=True),
        sa.Column("line_position", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=120), nullable=True),
        sa.Column("language", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("tradition_id", sa.String(length=36), nullable=True),
        sa.Column("exact_text", sa.Text(), nullable=False),
        sa.Column("locator", sa.String(length=500), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "line_position IS NULL OR line_position BETWEEN 1 AND 6",
            name="ck_iching_text_line_position",
        ),
        sa.ForeignKeyConstraint(["hexagram_id"], ["hexagrams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tradition_id"], ["traditions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trigram_id"], ["trigrams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_iching_text_key"),
    )
    with op.batch_alter_table("hexagrams", recreate="always") as batch:
        batch.add_column(sa.Column("key", sa.String(length=40), nullable=True))
        batch.add_column(sa.Column("pinyin", sa.String(length=120), nullable=True))
        batch.add_column(sa.Column("legge_title", sa.String(length=200), nullable=True))
        batch.add_column(sa.Column("lower_trigram_id", sa.String(length=36), nullable=True))
        batch.add_column(sa.Column("upper_trigram_id", sa.String(length=36), nullable=True))
        batch.create_unique_constraint("uq_hexagram_key", ["key"])
        batch.create_foreign_key(
            "fk_hexagram_upper_trigram",
            "trigrams",
            ["upper_trigram_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch.create_foreign_key(
            "fk_hexagram_lower_trigram",
            "trigrams",
            ["lower_trigram_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    with op.batch_alter_table("iching_throws", recreate="always") as batch:
        batch.add_column(sa.Column("procedure", sa.JSON(), nullable=True))
        batch.alter_column("coin_1", existing_type=sa.Integer(), nullable=True)
        batch.alter_column("coin_2", existing_type=sa.Integer(), nullable=True)
        batch.alter_column("coin_3", existing_type=sa.Integer(), nullable=True)
        batch.drop_constraint("ck_coin_1", type_="check")
        batch.drop_constraint("ck_coin_2", type_="check")
        batch.drop_constraint("ck_coin_3", type_="check")
        batch.drop_constraint("ck_line_value_coin_sum", type_="check")
        batch.create_check_constraint("ck_coin_1", "coin_1 IS NULL OR coin_1 IN (2,3)")
        batch.create_check_constraint("ck_coin_2", "coin_2 IS NULL OR coin_2 IN (2,3)")
        batch.create_check_constraint("ck_coin_3", "coin_3 IS NULL OR coin_3 IN (2,3)")
        batch.create_check_constraint(
            "ck_coin_presence",
            "(coin_1 IS NULL AND coin_2 IS NULL AND coin_3 IS NULL) OR "
            "(coin_1 IS NOT NULL AND coin_2 IS NOT NULL AND coin_3 IS NOT NULL)",
        )
        batch.create_check_constraint(
            "ck_line_value_coin_sum",
            "(coin_1 IS NULL AND coin_2 IS NULL AND coin_3 IS NULL) OR "
            "line_value = coin_1 + coin_2 + coin_3",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("iching_texts")
    op.drop_table("iching_relationships")
    op.drop_table("hexagram_lines")
    op.drop_table("iching_methods")
    with op.batch_alter_table("iching_throws", recreate="always") as batch:
        batch.drop_constraint("ck_coin_1", type_="check")
        batch.drop_constraint("ck_coin_2", type_="check")
        batch.drop_constraint("ck_coin_3", type_="check")
        batch.drop_constraint("ck_coin_presence", type_="check")
        batch.drop_constraint("ck_line_value_coin_sum", type_="check")
        batch.alter_column("coin_1", existing_type=sa.Integer(), nullable=False)
        batch.alter_column("coin_2", existing_type=sa.Integer(), nullable=False)
        batch.alter_column("coin_3", existing_type=sa.Integer(), nullable=False)
        batch.drop_column("procedure")
        batch.create_check_constraint("ck_coin_1", "coin_1 IN (2,3)")
        batch.create_check_constraint("ck_coin_2", "coin_2 IN (2,3)")
        batch.create_check_constraint("ck_coin_3", "coin_3 IN (2,3)")
        batch.create_check_constraint(
            "ck_line_value_coin_sum", "line_value = coin_1 + coin_2 + coin_3"
        )
    with op.batch_alter_table("hexagrams", recreate="always") as batch:
        batch.drop_constraint("fk_hexagram_upper_trigram", type_="foreignkey")
        batch.drop_constraint("fk_hexagram_lower_trigram", type_="foreignkey")
        batch.drop_constraint("uq_hexagram_key", type_="unique")
        batch.drop_column("upper_trigram_id")
        batch.drop_column("lower_trigram_id")
        batch.drop_column("legge_title")
        batch.drop_column("pinyin")
        batch.drop_column("key")
    op.drop_table("trigrams")
    # ### end Alembic commands ###
