"""initial schema

Revision ID: 78ccb39ffeb9
Revises:
Create Date: 2026-08-22 23:28:54.418753
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "78ccb39ffeb9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("system_type", sa.String(length=32), nullable=False),
        sa.Column("supports_reversals", sa.Boolean(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "system_type IN ('tarot','oracle','runes')", name="ck_collection_system"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "readings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("edition", sa.String(length=120), nullable=True),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=40), nullable=True),
        sa.Column("citation", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("rights_status", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spreads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "traditions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=80), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "slug", name="uq_item_collection_slug"),
    )
    op.create_table(
        "reading_casts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("reading_id", sa.String(length=36), nullable=False),
        sa.Column("cast_type", sa.String(length=32), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("cast_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("primary_pattern", sa.String(length=6), nullable=True),
        sa.Column("relating_pattern", sa.String(length=6), nullable=True),
        sa.Column("changing_lines", sa.JSON(), nullable=False),
        sa.CheckConstraint("cast_type IN ('collection','iching')", name="ck_cast_type"),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reading_id"], ["readings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reading_id", "cast_order", name="uq_reading_cast_order"),
    )
    op.create_table(
        "reading_notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("reading_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["reading_id"], ["readings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spread_positions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("spread_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("rotation", sa.Float(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.CheckConstraint('"order" >= 1', name="ck_spread_position_order"),
        sa.ForeignKeyConstraint(["spread_id"], ["spreads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spread_id", "order", name="uq_spread_position_order"),
    )
    op.create_table(
        "correspondences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("tradition_id", sa.String(length=36), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("locator", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('attested','disputed','tradition_specific','not_applicable','not_attested','unknown')",  # noqa: E501
            name="ck_correspondence_status",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tradition_id"], ["traditions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "draw_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cast_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("draw_order", sa.Integer(), nullable=False),
        sa.Column("orientation", sa.String(length=20), nullable=False),
        sa.CheckConstraint("orientation IN ('upright','reversed','none')", name="ck_orientation"),
        sa.ForeignKeyConstraint(["cast_id"], ["reading_casts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cast_id", "draw_order", name="uq_draw_order"),
        sa.UniqueConstraint("cast_id", "item_id", name="uq_cast_item"),
    )
    op.create_table(
        "iching_throws",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cast_id", sa.String(length=36), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("coin_1", sa.Integer(), nullable=False),
        sa.Column("coin_2", sa.Integer(), nullable=False),
        sa.Column("coin_3", sa.Integer(), nullable=False),
        sa.Column("line_value", sa.Integer(), nullable=False),
        sa.CheckConstraint("line_number BETWEEN 1 AND 6", name="ck_line_number"),
        sa.CheckConstraint("line_value IN (6,7,8,9)", name="ck_line_value"),
        sa.ForeignKeyConstraint(["cast_id"], ["reading_casts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cast_id", "line_number", name="uq_iching_line"),
    )
    op.create_table(
        "interpretations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("tradition_id", sa.String(length=36), nullable=True),
        sa.Column("interpretation_type", sa.String(length=40), nullable=False),
        sa.Column("exact_text", sa.Text(), nullable=False),
        sa.Column("locator", sa.String(length=200), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "interpretation_type IN ('upright','reversed','divinatory','symbolism','description','commentary')",  # noqa: E501
            name="ck_interpretation_type",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tradition_id"], ["traditions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "placements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cast_id", sa.String(length=36), nullable=False),
        sa.Column("draw_result_id", sa.String(length=36), nullable=False),
        sa.Column("spread_id", sa.String(length=36), nullable=True),
        sa.Column("spread_position_id", sa.String(length=36), nullable=True),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("rotation", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["cast_id"], ["reading_casts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["draw_result_id"], ["draw_results.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spread_id"], ["spreads.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["spread_position_id"], ["spread_positions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cast_id", "spread_position_id", name="uq_cast_position"),
        sa.UniqueConstraint("draw_result_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("placements")
    op.drop_table("interpretations")
    op.drop_table("iching_throws")
    op.drop_table("draw_results")
    op.drop_table("correspondences")
    op.drop_table("spread_positions")
    op.drop_table("reading_notes")
    op.drop_table("reading_casts")
    op.drop_table("items")
    op.drop_table("traditions")
    op.drop_table("spreads")
    op.drop_table("sources")
    op.drop_table("readings")
    op.drop_table("collections")
    # ### end Alembic commands ###
