"""add provenance-ready hexagram corpus

Revision ID: edda8e9cd334
Revises: 78ccb39ffeb9
Create Date: 2026-08-22 23:32:58.045458
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "edda8e9cd334"
down_revision: str | None = "78ccb39ffeb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hexagrams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("canonical_number", sa.Integer(), nullable=False),
        sa.Column("binary_pattern", sa.String(length=6), nullable=False),
        sa.Column("chinese_name", sa.String(length=120), nullable=True),
        sa.Column("glyph", sa.String(length=16), nullable=True),
        sa.Column("lower_trigram", sa.String(length=120), nullable=True),
        sa.Column("upper_trigram", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("canonical_number BETWEEN 1 AND 64", name="ck_hexagram_number"),
        sa.CheckConstraint("length(binary_pattern) = 6", name="ck_hexagram_pattern_length"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("binary_pattern"),
        sa.UniqueConstraint("canonical_number"),
    )
    op.create_table(
        "hexagram_texts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("hexagram_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("tradition_id", sa.String(length=36), nullable=True),
        sa.Column("text_type", sa.String(length=40), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=40), nullable=True),
        sa.Column("exact_text", sa.Text(), nullable=False),
        sa.Column("locator", sa.String(length=200), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "text_type IN ('original','translation','judgment','image','line','commentary')",
            name="ck_hexagram_text_type",
        ),
        sa.CheckConstraint(
            "line_number IS NULL OR line_number BETWEEN 1 AND 6", name="ck_hexagram_text_line"
        ),
        sa.ForeignKeyConstraint(["hexagram_id"], ["hexagrams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tradition_id"], ["traditions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hexagram_texts")
    op.drop_table("hexagrams")
    # ### end Alembic commands ###
